#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_update: true
package_upgrade: true
packages:

final_message: "######### Final Message ########"

runcmd:
    - /usr/libexec/oci-growfs -y
